# SPDX-License-Identifier: Apache-2.0
FROM node:25-trixie

ARG PI_MONO_VERSION=v0.67.6
ARG PI_MONO_GIT_REPO=https://github.com/badlogic/pi-mono.git

ENV PATH="$PATH:/root/.local/bin:/opt/agent/pi-mono/packages/coding-agent/dist" \
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
  PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Entrypoint:
COPY pi-run.sh /.pi/pi-run.sh
# The binary used to start the pi cli:
COPY pi /.pi/pi
# Package manager minimum release age configurations:
COPY .npmrc /.pi/dotfiles/.npmrc
COPY .pnpm-rc /.pi/dotfiles/.config/pnpm/rc
COPY .bunfig.toml /.pi/dotfiles/.bunfig.toml
COPY .config-uv-uv.toml /.pi/dotfiles/.config/uv/uv.toml

RUN mkdir -p ~/.local/bin \
  && apt update \
  && apt install -y curl fd-find ripgrep tree unzip zip \
  && ln -s "$(which fdfind)" ~/.local/bin/fd \
  && mkdir -p /opt/agent/pi-mono \
  && cd /opt/agent/pi-mono \
  && git clone "${PI_MONO_GIT_REPO}" . \
  && git checkout "${PI_MONO_VERSION}" \
  && echo " => install pi-mono dependencies" \
  && npm install \
  && echo " => build pi-mono" \
  && npm run build \
  && echo " => making required programs executable" \
  && chmod 0755 /.pi/pi-run.sh \
  && mv -v /.pi/pi /opt/agent/pi-mono/packages/coding-agent/dist/pi \
  && chmod 0755 /opt/agent/pi-mono/packages/coding-agent/dist/pi \
  && echo " => installing pi-mono-http-proxy" \
  && npm install --save "git://github.com/combust-labs/pi-mono-http-proxy.git#3ec12f7e68f0578369935810b669d08638e9d371" \
  && chmod 0755 /opt/agent/pi-mono/node_modules/pi-rpc-http-server/bin/run.sh \
  && echo " => install bun" \
  && curl -fsSL https://bun.com/install | bash \
  && echo " => install pnpm" \
  && curl -fsSL https://get.pnpm.io/install.sh | bash - \
  && echo " => dotfiles" \
  && mkdir -p ~/.config/pnpm \
  && mkdir -p ~/.config/uv \
  && ln -sF /.pi/dotfiles/.bunfig.toml ~/.bunfig.toml \
  && ln -sF /.pi/dotfiles/.npmrc ~/.npmrc \
  && ln -sF /.pi/dotfiles/.config/pnpm/rc ~/.config/pnpm/rc \
  && ln -sF /.pi/dotfiles/.config/uv/uv.toml ~/.config/uv/uv.toml

# RUN if [ "$(uname -m)" = "aarch64" ] ; then \
#   apt-get install -y chromium ; \
#   export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true ; \
#   export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser ; \
#   fi

VOLUME [".pi", "/code", "/sessions"]

WORKDIR /code

ENTRYPOINT ["/.pi/pi-run.sh"]
